hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

gravity_spy_path: ~/workspace/gw-noise-clustering/data/gravity_spy_labels.csv
dataset_path: ~/workspace/gw-noise-clustering/data/z-autoencoder-outputs.csv

verbose: True

labels: [1080Lines, 1400Ripples, Air_Compressor, Blip,
         Chirp, Extremely_Loud, Helix, Koi_Fish,
         Light_Modulation, Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
         None_of_the_Above, Paired_Doves, Power_Line, Repeating_Blips,
         Scattered_Light, Scratchy, Tomte, Violin_Mode,
         Wandering_Line, Whistle]

random_state: 123
umap:
  n_components: 3
  n_neighbors: 15
  min_dist: 0.3

sc:
  n_start: 10
  n_end: 35
  gamma: self_turning_neighbor:15
  # gamma: median-heuristic

bootstrap_num: 50
clustering_stability_nnk: 15

wandb:
  project: gw-noise-clustering
  group: feat-cs-knn
  name: clustering-stability
  cwd: current_work_directory
